#!/usr/bin/env bash
# Ember Browser — Chromium build script
# Fetches Chromium source, applies Ember patches, and builds via GN + Ninja.
#
# Usage:
#   ./build.sh [OPTIONS]
#
# Options:
#   --fetch        Fetch Chromium source (requires depot_tools in PATH)
#   --patch        Apply Ember patches to Chromium source
#   --configure    Generate GN build args
#   --build        Run Ninja build
#   --all          Fetch + patch + configure + build
#   --clean        Remove build output
#   --help         Show this help
#
# Environment:
#   EMBER_CHROMIUM_TAG    Chromium tag to check out (default: stable)
#   EMBER_BUILD_DIR       Build output directory (default: out/Default)
#   EMBER_JOBS            Parallel build jobs (default: nproc)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATCHES_DIR="${SCRIPT_DIR}/patches"

# --- Configuration ---

CHROMIUM_VERSION="${EMBER_CHROMIUM_TAG:-131.0.6778.85}"
BUILD_DIR="${EMBER_BUILD_DIR:-out/Default}"
JOBS="${EMBER_JOBS:-$(nproc)}"
CHROMIUM_SRC="${SCRIPT_DIR}/chromium/src"

# GN build args for Ember
GN_ARGS=(
    'is_official_build=true'
    'is_debug=false'
    'symbol_level=0'
    'chrome_pgo_phase=0'
    'is_component_build=false'
    'proprietary_codecs=false'
    'ffmpeg_branding="Chrome"'
    'enable_nacl=false'
    'use_sysroot=true'
    'use_goma=false'
    'use_siso=false'
    'is_clang=true'
    'use_lld=true'
    'dcheck_always_on=false'
    'treat_warnings_as_errors=false'
)

# --- Helpers ---

log() { echo -e "\033[1;32m[ember]\033[0m $*"; }
err() { echo -e "\033[1;31m[ember]\033[0m $*" >&2; exit 1; }

check_prereqs() {
    local missing=0
    for cmd in git python3 gn ninja; do
        if ! command -v "$cmd" &>/dev/null; then
            err "Missing required tool: $cmd"
            missing=1
        fi
    done
    [[ $missing -eq 1 ]] && exit 1
    log "All build prerequisites found."
}

# --- Fetch ---

fetch_chromium() {
    log "Fetching Chromium ${CHROMIUM_VERSION}..."

    if [[ ! -d "${SCRIPT_DIR}/chromium" ]]; then
        mkdir -p "${SCRIPT_DIR}/chromium"
    fi

    cd "${SCRIPT_DIR}/chromium"

    if [[ ! -d ".gclient" ]]; then
        cat > .gclient <<EOF
solutions = [{
  "name": "src",
  "url": "https://chromium.googlesource.com/chromium/src.git@${CHROMIUM_VERSION}",
  "managed": False,
  "custom_deps": {},
}]
EOF
        gclient sync --no-history --shallow --revision="src@${CHROMIUM_VERSION}"
    else
        log "Chromium source already present. Updating..."
        gclient sync --no-history --shallow
    fi

    log "Chromium source ready at ${CHROMIUM_SRC}"
}

# --- Patch ---

apply_patches() {
    log "Applying Ember patches..."

    if [[ ! -d "${CHROMIUM_SRC}" ]]; then
        err "Chromium source not found at ${CHROMIUM_SRC}. Run with --fetch first."
    fi

    cd "${CHROMIUM_SRC}"

    # Apply patches in order
    local patch_dirs=("degoogle" "privacy" "search" "shell")
    local patch_count=0

    for dir in "${patch_dirs[@]}"; do
        local patch_path="${PATCHES_DIR}/${dir}"
        if [[ -d "${patch_path}" ]]; then
            for patch in "${patch_path}"/*.patch; do
                [[ -f "$patch" ]] || continue
                log "  Applying: $(basename "$patch")"
                git apply --check "$patch" 2>/dev/null || {
                    log "  Patch already applied or conflicts: $(basename "$patch"), skipping."
                    continue
                }
                git apply "$patch"
                patch_count=$((patch_count + 1))
            done
        fi
    done

    log "Applied ${patch_count} patch(es)."
}

# --- Configure ---

configure_build() {
    log "Configuring GN build args..."

    if [[ ! -d "${CHROMIUM_SRC}" ]]; then
        err "Chromium source not found. Run with --fetch first."
    fi

    local gn_args_file="${CHROMIUM_SRC}/${BUILD_DIR}/args.gn"
    mkdir -p "${CHROMIUM_SRC}/${BUILD_DIR}"

    {
        echo "# Ember Browser build configuration"
        echo "# Generated by build.sh — do not edit manually"
        echo ""
        for arg in "${GN_ARGS[@]}"; do
            echo "${arg}"
        done
    } > "${gn_args_file}"

    cd "${CHROMIUM_SRC}"
    gn gen "${BUILD_DIR}"

    log "Build configured: ${gn_args_file}"
}

# --- Build ---

run_build() {
    log "Building Chromium with ${JOBS} parallel jobs..."

    if [[ ! -d "${CHROMIUM_SRC}/${BUILD_DIR}" ]]; then
        err "Build directory not found. Run with --configure first."
    fi

    cd "${CHROMIUM_SRC}"
    autoninja -C "${BUILD_DIR}" chrome

    log "Build complete. Binary at: ${CHROMIUM_SRC}/${BUILD_DIR}/chrome"
}

# --- Clean ---

clean_build() {
    log "Cleaning build output..."
    if [[ -d "${CHROMIUM_SRC}/${BUILD_DIR}" ]]; then
        rm -rf "${CHROMIUM_SRC}/${BUILD_DIR}"
        log "Build directory removed."
    else
        log "Nothing to clean."
    fi
}

# --- Main ---

usage() {
    head -n 16 "$0" | tail -n +2 | sed 's/^# \?//'
    exit 0
}

main() {
    [[ $# -eq 0 ]] && usage

    check_prereqs

    for arg in "$@"; do
        case "$arg" in
            --fetch)      fetch_chromium ;;
            --patch)      apply_patches ;;
            --configure)  configure_build ;;
            --build)      run_build ;;
            --all)
                fetch_chromium
                apply_patches
                configure_build
                run_build
                ;;
            --clean)      clean_build ;;
            --help|-h)    usage ;;
            *)            err "Unknown option: $arg" ;;
        esac
    done
}

main "$@"
